export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
export const AGREGAR_PROYECTO = 'AGREGAR_PROYECTO';
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';
export const PROYECTO_ACTUAL = 'PROYECTO_ACTUAL';
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';

export const OBTENER_TAREAS = 'OBTENER_TAREAS';
export const AGREGAR_TAREAS = 'AGREGAR_TAREAS';
export const PAGINADOR_TAREAS = 'PAGINADOR_TAREAS';